language: node_js

node_js:
  - "11"
  - "10"
  - "8"
  - "6"

# services:
#   - docker

before_script:
  - sudo /etc/init.d/mysql stop # - sudo systemctl stop mysql
  - npm run mariadb

script:
  - npm run lint
  - npm install -g nyc
  - nyc npm test

#after_script:
#  - npm run codecov:upload
after_success:
  - npm run codecov:upload

notifications:
  email:
    on_success: never
    on_failure: always
